In [1]:
import numpy as np 

In [ ]:

# Q1 — Weekly Step Counter (array creation & attributes)
# A fitness band records your steps for one week:

steps = [4523, 6712, 8934, 5210, 10432, 12045, 7642]
# Convert the list into a NumPy array.
array_steps = np.array(steps)
print(type(array_steps))
# Print its shape, size, ndim and dtype.
print(np.shape(array_steps))          
print(np.size(array_steps))           
print(np.ndim(array_steps))           
print(np.array(array_steps).dtype)

# Print the total steps for the week and the average steps per day.
print(f"total steps for the week is {sum(array_steps)} steps.")
print(f"Average steps per say is  {np.mean(array_steps)} steps.")

# In a comment, explain why a NumPy array is a better choice than a list
# because speed is higher , it array consume less memory and we can implement mathmatical operation 
# more convient way 

<class 'numpy.ndarray'>
(7,)
7
1
int64
total steps for the week is 55498 steps.
Average steps per say is  7928.285714285715 steps.


In [21]:
# Q2 — Cinema Seating Plan (zeros, ones, full)
# A new cinema hall has 12 rows and 16 seats per row.
# Create the empty hall as an array of zeros (0 = free seat).
hall = np.zeros((12,16))
print(hall)
# A private screening books the entire hall — create the same-shaped array filled with ones (1 = booked).
booked_hall = np.ones((12,16))
print(booked_hall)
# Ticket price is Rs. 450 for every seat — create a price grid of shape (12, 16) filled with 450 using np.full.
hall_cost = np.full((12,16),450)
print(hall_cost)
# Print the total revenue if the hall sells out (use the price grid, not arithmetic by hand).
print(f"Total revenue of the hall is Rs.{np.sum(hall_cost)}")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1

In [ ]:
# Q3 — Bus Departure Timetable (arange & linspace)
# A bus park manages departures from 6:00 (hour 6.0) to 21:00 (hour 21.0).

# Route A departs every 45 minutes starting at 6:00 — generate the departure times in hours 

# using np.arange (45 minutes = 0.75 hours). The last bus must not depart after 21:00.
route_a = np.arange (6,21, 0.75)
print(f" Depature time of Bus is: {route_a} ")
# Route B makes exactly 12 equally spaced departures between 6:00 and 21:00 inclusive — generate them with np.linspace.
# Print how many departures each route makes per day.
route_B = np.linspace(6 ,21,12)
print(route_B)
# In a comment, explain which function you would pick 
# when the interval is fixed vs when the number of trips is fixed.
i will use linspace when the interval and number of trips is fixed because 
linespace is efficent for it. 


 Depature time of Bus is: [ 6.    6.75  7.5   8.25  9.    9.75 10.5  11.25 12.   12.75 13.5  14.25
 15.   15.75 16.5  17.25 18.   18.75 19.5  20.25] 
[ 6.          7.36363636  8.72727273 10.09090909 11.45454545 12.81818182
 14.18181818 15.54545455 16.90909091 18.27272727 19.63636364 21.        ]


In [35]:
# Q4 — Exam Score Slicing (1D indexing & slicing)
# The scores of 20 students, in roll-number order:

scores = np.array([45, 78, 88, 56, 90, 62, 71, 84, 39, 95,
                   67, 73, 81, 58, 92, 49, 77, 85, 63, 70])
# Using only indexing/slicing (no loops, no conditions):
# The score of the first and the last student.
print(scores[[0,-1]])
# The scores of roll numbers 5 to 10 (inclusive).
print(scores[5:10])
# Every 3rd student's score, starting from roll number 1.
print(scores[0::3])
# The scores in reverse order.
print(scores[::-1])
# The five lowest-roll-numbered students' scores, excluding the very first student.
print(scores[1:5])





[45 70]
[62 71 84 39 95]
[45 56 71 95 81 49 63]
[70 63 85 77 49 92 58 81 73 67 95 39 84 71 62 90 56 88 78 45]
[78 88 56 90]


In [ ]:
# # Q5 — Daily Temperature Report (basic statistics)
# # Hourly temperatures (°C) in Kathmandu for one day:

# np.random.seed(15)
# temps = np.round(np.random.uniform(8, 27, 24), 1)
# Report the maximum, minimum, mean and standard deviation of the day.
# Report the median and explain in a comment when the median is a better summary than the mean.
# Find at which hour (index) the max and min occurred (argmax / argmin).
# The forecast said the average would be 18 °C — print by how many degrees the real mean missed the forecast.