In [1]:
import numpy as np 

In [3]:

# Q1 — Weekly Step Counter (array creation & attributes)
# A fitness band records your steps for one week:

steps = [4523, 6712, 8934, 5210, 10432, 12045, 7642]
# Convert the list into a NumPy array.
array_steps = np.array(steps)
print(type(array_steps))
# Print its shape, size, ndim and dtype.
print(np.shape(array_steps))          
print(np.size(array_steps))           
print(np.ndim(array_steps))           
print(np.array(array_steps).dtype)

# Print the total steps for the week and the average steps per day.
print(f"total steps for the week is {sum(array_steps)} steps.")
print(f"Average steps per say is  {np.mean(array_steps)} steps.")

# In a comment, explain why a NumPy array is a better choice than a list
# because speed is higher , it array consume less memory and we can implement mathmatical operation 
# more convient way 

<class 'numpy.ndarray'>
(7,)
7
1
int64
total steps for the week is 55498 steps.
Average steps per say is  7928.285714285715 steps.


In [4]:
# Q2 — Cinema Seating Plan (zeros, ones, full)
# A new cinema hall has 12 rows and 16 seats per row.
# Create the empty hall as an array of zeros (0 = free seat).
hall = np.zeros((12,16))
print(hall)
# A private screening books the entire hall — create the same-shaped array filled with ones (1 = booked).
booked_hall = np.ones((12,16))
print(booked_hall)
# Ticket price is Rs. 450 for every seat — create a price grid of shape (12, 16) filled with 450 using np.full.
hall_cost = np.full((12,16),450)
print(hall_cost)
# Print the total revenue if the hall sells out (use the price grid, not arithmetic by hand).
print(f"Total revenue of the hall is Rs.{np.sum(hall_cost)}")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1

In [5]:
# Q3 — Bus Departure Timetable (arange & linspace)
# A bus park manages departures from 6:00 (hour 6.0) to 21:00 (hour 21.0).

# Route A departs every 45 minutes starting at 6:00 — generate the departure times in hours 

# using np.arange (45 minutes = 0.75 hours). The last bus must not depart after 21:00.
route_a = np.arange (6,21, 0.75)
print(f" Depature time of Bus is: {route_a} ")
# Route B makes exactly 12 equally spaced departures between 6:00 and 21:00 inclusive — generate them with np.linspace.
# Print how many departures each route makes per day.
route_B = np.linspace(6 ,21,12)
print(route_B)
# In a comment, explain which function you would pick 
# when the interval is fixed vs when the number of trips is fixed.
# i will use linspace when the interval and number of trips is fixed because 
# linespace is efficent for it. 


 Depature time of Bus is: [ 6.    6.75  7.5   8.25  9.    9.75 10.5  11.25 12.   12.75 13.5  14.25
 15.   15.75 16.5  17.25 18.   18.75 19.5  20.25] 
[ 6.          7.36363636  8.72727273 10.09090909 11.45454545 12.81818182
 14.18181818 15.54545455 16.90909091 18.27272727 19.63636364 21.        ]


In [6]:
# Q4 — Exam Score Slicing (1D indexing & slicing)
# The scores of 20 students, in roll-number order:

scores = np.array([45, 78, 88, 56, 90, 62, 71, 84, 39, 95,
                   67, 73, 81, 58, 92, 49, 77, 85, 63, 70])
# Using only indexing/slicing (no loops, no conditions):
# The score of the first and the last student.
print(scores[[0,-1]])
# The scores of roll numbers 5 to 10 (inclusive).
print(scores[5:10])
# Every 3rd student's score, starting from roll number 1.
print(scores[0::3])
# The scores in reverse order.
print(scores[::-1])
# The five lowest-roll-numbered students' scores, excluding the very first student.
print(scores[1:5])





[45 70]
[62 71 84 39 95]
[45 56 71 95 81 49 63]
[70 63 85 77 49 92 58 81 73 67 95 39 84 71 62 90 56 88 78 45]
[78 88 56 90]


In [7]:
# # Q5 — Daily Temperature Report (basic statistics)
# # Hourly temperatures (°C) in Kathmandu for one day:

np.random.seed(15)
temps = np.round(np.random.uniform(8, 27, 24), 1)
# Report the maximum, minimum, mean and standard deviation of the day.
print(f"maximun temperature will be {temps.max()}degree celsious ")
print(f"minimum temperature will be {temps.min()} degree celcious" )
print(f"average temperature will be {temps.mean()} degree celcious" )
print(temps.std())

# Report the median and explain in a comment when the median is a better summary than the mean.
# if data have outlier median is better in those cases. 
# Find at which hour (index) the max and min occurred (argmax / argmin).
print(f"Max temperature at hour index {temps.argmax()}") 
print(f"Min temperature at hour index {temps.argmin()}")
# The forecast said the average would be 18 °C — print by how many degrees the real mean missed the forecast.
forecast = 18
miss = temps.mean() - forecast
print(f"The real mean missed the forecast by {miss:.1f} °C")



maximun temperature will be 27.0degree celsious 
minimum temperature will be 8.7 degree celcious
average temperature will be 15.954166666666666 degree celcious
5.705551329382834
Max temperature at hour index 20
Min temperature at hour index 18
The real mean missed the forecast by -2.0 °C


# Intermediate

In [ ]:

# Q6 — Supermarket Sales Grid (2D indexing & slicing)
# Daily sales (units) of 5 products across 7 days — rows = products, columns = days (Sun–Sat):

np.random.seed(6)
sales = np.random.randint(20, 200, (5, 7))
print(sales)
# Extract product 3's sales for the whole week.
print(f" 3's products salrs for the whole wees are {sales[3,:]}")
# Extract Friday's sales (6th column) for every product.
print(f"friday sales for every product are {sales[:,6]}")
# Extract the weekend sales (last 2 columns) for the first 3 products as one block.
print(f" weekend sales are  are: \n {sales[0:3,5:7]}")
# Using fancy indexing, pull out products 0, 2 and 4 in a single expression.
print(f"Fancy indexing{sales[0]}")
# Print the best-selling product's row total and its row index.




[[158 126 129  99 126 100  82]
 [ 45  21  95  97  46 181 130]
 [ 88 181  28 150  51 153 145]
 [174  35 106 134 191 197 152]
 [ 82 100 147  86  83 167 105]]
 3's products salrs for the whole wees are [174  35 106 134 191 197 152]
friday sales for every product are [ 82 130 145 152 105]
 weekend sales are  are: 
 [[100  82]
 [181 130]
 [153 145]]


In [ ]:
# Q7 — Student Marksheet Analytics (axis-wise statistics)
# Marks of 6 students in 4 subjects — rows = students, columns = [Math, Science, English, Computer]:

np.random.seed(7)
marks = np.random.randint(35, 100, (6, 4))
print(marks)
# Each student's average mark (one number per student — pick the correct axis).
print(f" the average marks of student is {np.mean(marks, axis=1 )} marks.")
# Each subject's highest mark (one number per subject).
print(f"Higest marks of student is  {np.max(marks, axis= 1 )} marks.")
# The overall class average.
print(f"overall average marks in class is {np.mean(marks)} Marks.")
# Which subject has the widest spread of marks (largest standard deviation)?
print(f" widest spread marks of subjects are {np.std(marks, axis=1 )} marks.")
# In a comment, explain in one sentence what axis=0 and axis=1 each mean here.


[[82 60 58 92]
 [49 58 77 43]
 [74 83 42 79]
 [35 90 41 54]
 [95 79 98 91]
 [59 90 88 96]]
 the average marks of student is [73.   56.75 69.5  55.   90.75 83.25] marks.
Higest marks of student is  [92 77 83 90 98 96] marks.
overall average marks in class is 71.375 Marks.
 widest spread marks of subjects are [14.45683229 12.85252893 16.19413474 21.34244597  7.22409164 14.30690393] marks.


In [ ]:
# Q8 — Image Thumbnail Maker (reshaping & transpose)
# A grayscale image arrives from a sensor as a flat stream of 144 pixel values:

np.random.seed(8)
stream = np.random.randint(0, 256, 144)
print(stream)
# Reshape the stream into a 12 × 12 image.

# The sensor was mounted sideways — fix the orientation with a transpose.

# Produce a flattened copy of the corrected image and confirm its shape is (144,).

# Reshape the stream into shape (6, -1) and print the resulting shape. In a comment, explain what the -1 did.

# Try reshaping the stream to (10, 15) inside a try/except block and print the error message. Explain in a comment why it fails.

[195  84 241 105 133 218 136  83 104 191  48 109  85  60 177 115 202 155
 108  13 137  61 143  93  98  59  18  14 102  93 184   9  51 196 181  53
  71  59 170 105 154  66 102   9 229 125 238  81 107  15 220  91 235  63
  86  31  20 173  21 200 220  28 223  47 138  64 135 173   2 166 199 223
  36 123 120 217 188 102  91 196  37 107 194 210  38  54 214 167 122  46
 105 134  95 160  73 226   7 126 137 226 230 170  19  59  48 137  16 112
 206 118 249 183 244 183 105  20 248  98 215 226 152   6 255 156 133  66
 147 227  75  11 174 220 200 183 217 142 167 143 147  58 104 112 125 119]


In [11]:
# Q9 — Merging Branch Reports (concatenate, vstack, hstack, stack)
# Two store branches report the same 4 products (rows) over 5 days (columns):

# np.random.seed(9)
# branch_ktm = np.random.randint(10, 100, (4, 5))
# branch_pkr = np.random.randint(10, 100, (4, 5))
# Head office wants one long table of 8 product rows — join them vertically.
# A second report needs the two weeks side by side as 10 columns — join them horizontally.
# A data engineer wants a single 3D array of shape (2, 4, 5) keeping the branches separable — use np.stack.
# A third branch opened mid-week and sends the same 4 products but only 4 days of data: branch_new = np.random.randint(10, 100, (4, 4)).
#  Attempt the vertical join with all three branches inside try/except, print the error, and explain in a comment which join is still possible with this branch and why.

In [12]:
# Q10 — Currency Conversion Table (broadcasting basics)
# An online store lists prices in USD:

# prices_usd = np.array([12.99, 45.50, 7.25, 99.00, 250.00, 3.75])
# Convert all prices to NPR in one expression (1 USD = 138.5 NPR) — no loops.
# The store offers a festival discount of 10% — compute the discounted NPR prices in one expression.
# Explain in a comment what NumPy did with the scalars 138.5 and 0.9 (name the mechanism).
# Delivery charges differ per item: delivery = np.array([50, 100, 50, 150, 500, 50]) (NPR). Compute the final payable amount per item. State in a comment which broadcasting case this is (scalar or same-shape).

# Advanced 

In [ ]:

# Q11 — Restaurant Bill Matrix (row & column broadcasting)
# A restaurant tracks the quantity of 4 dishes ordered by 5 tables — rows = tables, columns = dishes:

# np.random.seed(11)
# qty = np.random.randint(0, 4, (5, 4))
# dish_price = np.array([250, 480, 120, 350])       # price per dish
# table_discount = np.array([0, 5, 0, 10, 15])       # percent discount per table
# Compute the bill contribution of every cell (qty × price) in one broadcasted expression.
# Compute each table's subtotal (one number per table).
# Apply each table's percentage discount to its subtotal using broadcasting — think about which array needs reshaping to (5, 1) and which does not, and explain your choice in a comment.
# Print the restaurant's total collected revenue after discounts.

In [ ]:
# Q12 — Sensor Data Quality Check (statistics + percentiles)
# A weather station logs 200 humidity readings, but the sensor occasionally glitches:

# np.random.seed(12)
# humidity = np.random.normal(65, 8, 200)
# humidity[np.random.randint(0, 200, 5)] = [140, -20, 155, 190, -35]   # glitches
# Compute Q1, the median and Q3 with a single call to np.percentile.
# Compute the IQR and the outlier fences: low = Q1 - 1.5*IQR, high = Q3 + 1.5*IQR.
# Count how many readings fall outside the fences (boolean comparison + sum — no loops).
# Report the mean before cleaning, then the mean of only the in-range readings, and state in a comment which statistic (mean or median) changed less and why

In [ ]:
# Q13 — Class Photo Assembly (3D arrays + joining)
# A school scans 3 small grayscale ID photos, each 4 × 4 pixels:

# np.random.seed(13)
# photo1 = np.random.randint(0, 256, (4, 4))
# photo2 = np.random.randint(0, 256, (4, 4))
# photo3 = np.random.randint(0, 256, (4, 4))
# Stack the three photos into a single batch of shape (3, 4, 4) — the standard "batch of images" layout used in machine learning.
# From the batch, extract: (a) the entire second photo, (b) the top-left 2 × 2 corner of every photo in one expression.
# Compute the average photo (element-wise mean across the batch — pick the right axis) and verify its shape is (4, 4).
# Create a horizontal "film strip" of shape (4, 12) by joining the three photos side by side.

In [ ]:
# Q14 — Normalizing Exam Results (broadcasting + axis statistics combined)
# Results of 8 students across 3 subjects, where each subject was scored on a different scale:

# np.random.seed(14)
# raw = np.random.randint(20, 100, (8, 3)).astype(float)
# full_marks = np.array([100, 50, 80])    # each subject's maximum possible mark
# Convert every mark to a percentage of its subject's full marks in one broadcasted expression.
# Standardize each subject: subtract the subject's mean and divide by the subject's standard deviation (compute both with axis=0). This is the z-score used everywhere in machine learning.
# Verify your work: print each subject's mean and std after standardization (they should be approximately 0 and 1).
# Using the z-scores, find the roll number (row index) of the best all-round student (highest mean z-score across subjects).

# Mini: Capstone project 

In [ ]:
# Q15 — Mini Weather Dashboard (capstone: everything combined)
# A station records temperature 4 times a day (06:00, 12:00, 18:00, 00:00) for 4 weeks (28 days):

# np.random.seed(20)
# readings = np.round(np.random.uniform(5, 32, 28 * 4), 1)   # flat stream, oldest first
# Build a small report that prints:

# Reshape the flat stream into shape (28, 4) — days × time-slots — and then into (4, 7, 4) — weeks × days × time-slots.
# The average temperature of each week (4 numbers) and of each time slot across the whole month (4 numbers). Label which axis you reduced for each, in comments.
# The hottest single reading of the month and which week, day and slot it occurred in (use np.argmax with np.unravel_index).
# The daily range (daily max − daily min) for all 28 days in one expression, and the day with the largest range.
# Week-over-week comparison: using broadcasting, subtract week 1's daily-average pattern (7 numbers) from every week's daily averages (4, 7) and print the result — positive numbers mean warmer than week 1.